# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-13 06:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='nombre del proyecto')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripcion del proyecto')),
                ('file', models.FileField(blank=True, null=True, upload_to='Proyectos', verbose_name='proyecto')),
                ('slug', models.CharField(max_length=500, verbose_name='slug')),
                ('state', models.BooleanField(default=True, verbose_name='Estado del proyecto')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='fecha de modificacion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Propietario')),
            ],
            options={
                'ordering': ['name'],
                'db_table': 'Projects',
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
            },
        ),
    ]
