# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-02-02 07:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'ordering': ['-created_date'], 'verbose_name': 'Proyecto', 'verbose_name_plural': 'Proyectos'},
        ),
        migrations.AddField(
            model_name='categorysprojects',
            name='icon',
            field=models.CharField(blank=True, max_length=50, verbose_name='icon name'),
        ),
        migrations.AddField(
            model_name='projects',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='Images', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='categorysprojects',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='Category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Category', to='projects.CategorysProjects', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='slug',
            field=models.SlugField(max_length=100, null=True, verbose_name='Slug'),
        ),
    ]
