# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-01-30 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorysprojects',
            name='icon',
            field=models.CharField(blank=True, max_length=50, verbose_name='icon name'),
        ),
    ]
