# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-05 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20180202_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='description',
            field=models.TextField(default=1, verbose_name='Descripcion del proyecto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projects',
            name='file',
            field=models.FileField(default=1, upload_to='Proyectos', verbose_name='proyecto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projects',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, verbose_name='Slug'),
        ),
    ]
