# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-01-31 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_categorysprojects_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='Images', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='categorysprojects',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='slug',
            field=models.SlugField(max_length=100, null=True, verbose_name='Slug'),
        ),
    ]
