# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-02-02 07:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='Documentos', verbose_name='documento')),
                ('state', models.BooleanField(default=True, verbose_name='Estado de la verificacion')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='fecha de modificacion')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Profiles')),
            ],
            options={
                'db_table': 'Verification',
                'verbose_name': 'Verification',
                'verbose_name_plural': 'Verifications',
            },
        ),
    ]
