# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-01-31 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='state',
            field=models.BooleanField(default=True, verbose_name='Estado de la verificacion'),
        ),
    ]
